"""initial migration

Revision ID: 2e6c06ead0f4
Revises: 344648745ca6
Create Date: 2024-09-16 02:02:44.115930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6c06ead0f4'
down_revision = '344648745ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
