"""Initial migration

Revision ID: a72bbdb50ccc
Revises: 2e6c06ead0f4
Create Date: 2024-09-17 00:18:41.024481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72bbdb50ccc'
down_revision = '2e6c06ead0f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
